### ISSUE TITLE
App crashes when freshly installed.

### ISSUE THREAD

**Issue by kyleb000** [kyleb000/Plan-It-To-Do-App#22]
This is a major problem. On a phone where the app has never existed on before, it crashes when it is installed on that phone for the first time. I uninstalled the app and reinstalled it, but it crashed when it tried to run. I even tried a phone where the app has never been on before. Same story.

Here is the message:

 --------- beginning of crash
07-02 19:15:33.746 30866-30866/za.co.brdsa.kyle.planitto_doapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: za.co.brdsa.kyle.planitto_doapp, PID: 30866
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{za.co.brdsa.kyle.planitto_doapp/za.co.brdsa.kyle.planitto_doapp.MainActivity}: android.database.sqlite.SQLiteException: table task already exists (code 1): , while compiling: CREATE TABLE task(ID INTEGER PRIMARY KEY AUTOINCREMENT,task_name TEXT, task_description TEXT )
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2344)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5319)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
                                                                                  Caused by: android.database.sqlite.SQLiteException: table task already exists (code 1): , while compiling: CREATE TABLE task(ID INTEGER PRIMARY KEY AUTOINCREMENT,task_name TEXT, task_description TEXT )
                                                                                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:901)
                                                                                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:512)
                                                                                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
                                                                                     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                                                     at za.co.brdsa.kyle.planitto_doapp.controllers.DBHelper.onCreate(DBHelper.java:50)
                                                                                     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                                     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                     at za.co.brdsa.kyle.planitto_doapp.controllers.DatabaseManager.openDatabase(DatabaseManager.java:63)
                                                                                     at za.co.brdsa.kyle.planitto_doapp.queries.TaskQuery.getAllIncompleteToDos(TaskQuery.java:193)
                                                                                     at za.co.brdsa.kyle.planitto_doapp.views.TaskListFragment.onCreateView(TaskListFragment.java:54)
                                                                                     at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:833)
                                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                                     at android.app.Activity.performStart(Activity.java:5991)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5319) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method)

**Comment by kyleb000** [comment]
Never mind. I've fixed it
