### ISSUE TITLE
Add Notification support for API 16 and older 

### ISSUE THREAD

**Issue by JonoTheWhite** [kyleb000/Plan-It-To-Do-App#25]
NotifySetter.java Crashes due to no support on API 16 and earlier.
Lines 52 and 53 
setGroup
addAction

need to be changed

FATAL EXCEPTION: main
                                                                               Process: za.co.brdsa.kyle.planitto_doapp, PID: 3893
                                                                               java.lang.NoSuchMethodError: android.app.Notification$Builder.setGroup
                                                                                   at za.co.brdsa.kyle.planitto_doapp.NotifySetter.notifySet(NotifySetter.java:45)
                                                                                   at za.co.brdsa.kyle.planitto_doapp.NotifySetter.onReceive(NotifySetter.java:25)

**Comment by kyleb000** [comment]
Fixed
